FROM ruby:3.1.2-slim

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev curl git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile Gemfile.lock* ./
RUN bundle install

COPY . .

EXPOSE 3000
