source "https://rubygems.org"

ruby "3.1.2"

gem "rails", "~> 7.1.6"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]

gem "bcrypt", "~> 3.1.7"
gem "rack-cors"
gem "jwt"
gem "redis", ">= 4.0.1"
gem "sidekiq", "~> 7.2"
gem "sidekiq-cron", "~> 1.12"
gem "neighbor"
gem "pagy"
gem "aws-sdk-s3", require: false
gem "pdf-reader"
gem "stripe", "~> 12.0"
gem "pundit", "~> 2.3"

group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
  gem "dotenv-rails"
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
end

group :test do
  gem "webmock"
end

group :development do
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end
