# frozen_string_literal: true

# End-to-end report-quality harness. Drives the full pipeline against the LOCAL
# Gemma model (LM Studio) and self-checks every phase. Run:
#   docker exec req_app-rails-1 bundle exec rails runner /app/tmp/report_e2e.rb

# --- Point the OpenAI client at local Gemma -------------------------------
ENV["OPENAI_BASE_URL"]   = "http://host.docker.internal:1234/v1"
ENV["OPENAI_API_KEY"]    = "lm-studio"
ENV["OPENAI_MODEL"]      = "google/gemma-4-12b-qat"
ENV["REPORT_MODEL"]      = "google/gemma-4-12b-qat"
ENV["OPENAI_JSON_MODE"]  = "false"
ENV["OPENAI_MAX_TOKENS"] = "2500"
ENV["OPENAI_READ_TIMEOUT"] = "600"
ENV["AI_REPORT_NARRATIVE"] = "true"

$checks = []
$obs = []
def check(label, cond)
  $checks << [cond ? "PASS" : "FAIL", label]
  puts "[#{cond ? 'PASS' : 'FAIL'}] #{label}"
end
def observe(label, val)
  $obs << [label, val]
  puts "  · #{label}: #{val}"
end

puts "=" * 70
puts "REPORT E2E — model: #{ENV['OPENAI_MODEL']} @ #{ENV['OPENAI_BASE_URL']}"
puts "=" * 70

cl = Openai::Client.new
check("LLM client configured (base URL + key)", cl.configured? && cl.send(:chat_base_url).start_with?("http"))

# --- Setup: company with real evidence + an owned solution ----------------
company = Company.find_by(slug: "acme-corp") || Company.first
raise "no company" unless company

company.company_systems.owned_solutions.destroy_all
sol = company.company_systems.create!(
  name: "AcmeFlow HR Copilot", kind: "owned_solution", source: "manual", category: "other",
  description: "In-house AI copilot that automates manual onboarding paperwork and HR data entry.",
  capabilities: "onboarding automation, document generation, employee Q&A",
  normalized_name: CompanySystem.normalize("AcmeFlow HR Copilot")
)
observe("company", "#{company.name} (signals=#{company.company_signals.count}, patterns=#{company.patterns.count}, recs=#{company.recommendations.published.count})")
observe("owned solution", sol.name)

# ==========================================================================
# PHASE 2 — LLM analyst/writer (Gemma)
# ==========================================================================
puts "\n--- PHASE 2: narrative writer (Gemma) ---"
t0 = Time.now
snapshot = Reports::SnapshotBuilder.call(company: company, delta: {})
gen_secs = (Time.now - t0).round(1)
observe("snapshot build + narrative latency", "#{gen_secs}s")

narrative = snapshot["narrative"]
check("narrative generated by LLM", narrative.is_a?(Hash) && narrative["generated_by"] == "llm")
if narrative
  observe("governing_thought", narrative["governing_thought"].to_s.truncate(140))
  observe("executive_summary", narrative["executive_summary"].to_s.truncate(160))
  observe("supporting_points", Array(narrative["supporting_points"]).size)
  rm = narrative["roadmap"] || {}
  observe("roadmap now/next/later", "#{Array(rm['now']).size}/#{Array(rm['next']).size}/#{Array(rm['later']).size}")
  check("roadmap has at least one phased item", %w[now next later].any? { |p| Array(rm[p]).any? })
  check("exec summary is NOT the old templated Mad-Libs", !snapshot["executive_summary"].to_s.include?("The pages that follow show what we found"))
end

# ==========================================================================
# PHASE 4 — owned solutions fit + heatmap
# ==========================================================================
puts "\n--- PHASE 4: owned solutions + heatmap ---"
owned = Array(snapshot["owned_solutions"])
check("owned solution surfaced in snapshot", owned.any? { |o| o["name"] == sol.name })
os = owned.first
if os
  observe("owned fit_confidence", os["fit_confidence"])
  observe("owned addresses_signals", Array(os["addresses_signals"]).join(", ").presence || "(none)")
  check("owned fit confidence in 0..1", os["fit_confidence"].to_f.between?(0, 1))
end

# ==========================================================================
# PHASE 1 — credibility, rendered HTML
# ==========================================================================
puts "\n--- PHASE 1: credibility (rendered) ---"
html = Reports::HtmlBuilder.call(snapshot: snapshot, report_version: 99)
check("cover honors report_kind label", html.include?("#{snapshot['report_kind'] == 'baseline' ? 'Baseline' : 'Discovery'} Report"))
check("no placeholder example.com leaked", !html.include?("example.com"))
check("no debug match-strings leaked", !html.match?(/tag_match:|keyword_match:/))
check("plain-language strength band present", html.match?(/High|Medium|Low/) )
check("existing-capabilities section rendered", html.include?("What you already own"))
check("roadmap section rendered", html.include?("A sequenced path"))
heat = html.include?("Friction intensity by department")
observe("department heatmap rendered", heat ? "yes" : "no (needs >=2 depts with signals)")

# ==========================================================================
# Full pipeline — GenerateReportService (PDF via Gotenberg + MinIO)
# ==========================================================================
puts "\n--- FULL PIPELINE: GenerateReportService ---"
admin = company.company_users.first
version = (company.reports.maximum(:version) || 0) + 1
report = company.reports.create!(version: version, status: "queued", visibility: "internal_only",
                                 triggered_by_type: "CompanyUser", triggered_by_id: admin&.id,
                                 report_snapshot: {}, review_workflow_status: "awaiting_reviewers")
begin
  Reports::GenerateReportService.call(report: report)
  report.reload
  check("report generated to :ready", report.status == "ready")
  observe("artifact content_type", report.content_type)
  observe("storage_key", report.storage_key)
  check("stored snapshot carries LLM narrative", report.report_snapshot.dig("narrative", "generated_by") == "llm")
rescue => e
  check("GenerateReportService ran without error", false)
  observe("generate error", "#{e.class}: #{e.message}")
end

# ==========================================================================
# PHASE 3 — reviewer editorial control (hide / edit / add) + endorse
# ==========================================================================
puts "\n--- PHASE 3: reviewer editorial control ---"
reviewer = ReviewerUser.find_by(email: "reviewer@reqapp.local") || ReviewerUser.first
report.report_section_overrides.destroy_all
report.report_section_overrides.create!(reviewer_user: reviewer, action: "hide", section_key: "methodology")
report.report_section_overrides.create!(reviewer_user: reviewer, action: "edit", section_key: "recommendations",
                                        title: "Reviewer caveat", body: "Sequence the finance automation before HR — higher volume.")
report.report_section_overrides.create!(reviewer_user: reviewer, action: "add", title: "Risk register",
                                        body: "Demurrage exposure at Jebel Ali if customs clearance slips.", anchor_section: "recommendations")
# reviewer endorses the owned solution (mirrors the endorse endpoint)
sol.update!(reviewer_endorsed: true, reviewer_note: "Strong fit for onboarding load.", reviewer_user: reviewer)

applied = Reports::SectionOverridesApplier.call(snapshot: report.report_snapshot, report: report)
html2 = Reports::HtmlBuilder.call(snapshot: applied, report_version: report.version)
check("hidden section removed from body", !html2.include?("How we measured"))
check("hidden section removed from contents", !html2.include?(">Methodology<"))
check("reviewer edit-note rendered", html2.include?("Reviewer caveat") || html2.include?("Sequence the finance automation"))
check("custom reviewer section rendered", html2.include?("Risk register") && html2.include?("Demurrage exposure at Jebel Ali"))

owned2 = Array(Reports::SnapshotBuilder.new(company: company, delta: {}).send(:owned_solutions_json)).first
check("reviewer endorsement reflected on owned solution", owned2 && owned2["reviewer_endorsed"] == true)

# RegenerateWithReviewService end-to-end (approval path)
begin
  Reports::RegenerateWithReviewService.call(report: report.reload)
  check("RegenerateWithReviewService ran without error", true)
rescue => e
  check("RegenerateWithReviewService ran without error", false)
  observe("regenerate error", "#{e.class}: #{e.message}")
end

# ==========================================================================
# FALLBACK — deterministic when narrative disabled
# ==========================================================================
puts "\n--- FALLBACK: AI_REPORT_NARRATIVE=false ---"
ENV["AI_REPORT_NARRATIVE"] = "false"
snap_fb = Reports::SnapshotBuilder.call(company: company, delta: {})
check("narrative nil when disabled", snap_fb["narrative"].nil?)
html_fb = Reports::HtmlBuilder.call(snapshot: snap_fb, report_version: 100)
check("deterministic report still renders", html_fb.include?("Executive summary") && html_fb.length > 5000)
check("no roadmap section when narrative off", !html_fb.include?("A sequenced path"))

# ==========================================================================
# SUMMARY + OBSERVATIONS FILE
# ==========================================================================
passed = $checks.count { |s, _| s == "PASS" }
failed = $checks.count { |s, _| s == "FAIL" }
puts "\n" + "=" * 70
puts "RESULT: #{passed} passed, #{failed} failed, of #{$checks.size} checks"
puts "=" * 70

md = +"# Report Quality — E2E Observations (local Gemma)\n\n"
md << "- Model: `#{ENV['OPENAI_MODEL']}` via LM Studio\n"
md << "- Narrative latency: #{gen_secs}s\n"
md << "- Result: **#{passed}/#{$checks.size} checks passed** (#{failed} failed)\n\n"
md << "## Checks\n\n"
$checks.each { |s, l| md << "- #{s == 'PASS' ? '✅' : '❌'} #{l}\n" }
md << "\n## Observations\n\n"
$obs.each { |l, v| md << "- **#{l}:** #{v}\n" }
if narrative
  md << "\n## Sample narrative (Gemma)\n\n"
  md << "**Governing thought:** #{narrative['governing_thought']}\n\n"
  md << "**Executive summary:** #{narrative['executive_summary']}\n\n"
  md << "**Roadmap — Now:** #{Array(narrative.dig('roadmap','now')).map { |x| x['title'] }.join('; ')}\n\n"
  md << "**Roadmap — Next:** #{Array(narrative.dig('roadmap','next')).map { |x| x['title'] }.join('; ')}\n\n"
  md << "**Roadmap — Later:** #{Array(narrative.dig('roadmap','later')).map { |x| x['title'] }.join('; ')}\n"
end
File.write("/app/tmp/REPORT_E2E_OBSERVATIONS.md", md)
puts "Wrote /app/tmp/REPORT_E2E_OBSERVATIONS.md"
